{
 "title": "Api monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Total requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(django_http_requests_total_by_method_total{instance=\"app:8000\"}[$__rate_interval])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Status codes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "rate(django_http_responses_total_by_status_total{instance=\"app:8000\"}[$__rate_interval])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Payload bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(django_http_responses_body_total_bytes_sum{instance=\"app:8000\"}[$__rate_interval])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(django_http_requests_latency_including_middlewares_seconds_sum{instance=\"app:8000\"}[$__rate_interval])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "CPU ms",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"app:8000\"}[$__rate_interval])",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}